### ISSUE TITLE
Feature suggestion: Translation/Polishing or Custom Prompt

### ISSUE THREAD

**Issue by thedavidweng** [missuo/bob-plugin-copilot#1]
<img width="425" alt="Screenshot 2024-02-04 at 3 51 50 PM" src="https://github.com/missuo/bob-plugin-copilot/assets/95214375/b9532774-4d4c-4f21-892c-3dd80ea1da52">
增加“润色”模式或自定义 Prompt

**Comment by missuo** [comment]
Good suggestion! Welcome to submit PR.

**Comment by missuo** [comment]
When the source language and the target language are the same, the polishing function will be used automatically.

**Comment by thedavidweng** [comment]
> Good suggestion! Welcome to submit PR.

Sure, let me see see your prompt

**Comment by missuo** [comment]
Done. [v1.0.2](https://github.com/missuo/bob-plugin-copilot/releases/download/v1.0.2/bob-plugin-copilot-1.0.2.bobplugin)
