### ISSUE TITLE
1.0.3 更新提示“插件安装包完整性校验失败”

### ISSUE THREAD

**Issue by thedavidweng** [missuo/bob-plugin-copilot#4]
<img width="449" alt="Screenshot 2024-02-06 at 2 42 32 AM" src="https://github.com/missuo/bob-plugin-copilot/assets/95214375/8dc18731-c881-448e-ab69-e0ddf62d46bc">

**Comment by FaiChou** [comment]
卸载这个插件，重新下载安装最新版本。

**Comment by missuo** [comment]
已经移除不可用的 v1.0.3
